-------------------------------
-- Insert em Cores de Aluminios
--------------------------------
INSERT INTO CORES VALUES(1, 'Vermelho');
INSERT INTO CORES VALUES(2, 'Preto');
INSERT INTO CORES VALUES(3, 'Branco');
INSERT INTO CORES VALUES(4, 'Dourado');
INSERT INTO CORES VALUES(5, 'Amarelo');
INSERT INTO CORES VALUES(6, 'Prata');
INSERT INTO CORES VALUES(7, 'Cinza');
INSERT INTO CORES VALUES(8, 'Verde');
INSERT INTO CORES VALUES(9, 'Alumínio');
INSERT INTO CORES VALUES(10, 'Azul');

-------------------------------
-- Insert em Expessuras de vidro
--------------------------------
INSERT INTO EXPESSURA VALUES(1, 1);
INSERT INTO EXPESSURA VALUES(2, 2);
INSERT INTO EXPESSURA VALUES(3, 3);
INSERT INTO EXPESSURA VALUES(4, 4);
INSERT INTO EXPESSURA VALUES(5, 5);
INSERT INTO EXPESSURA VALUES(6, 6);
INSERT INTO EXPESSURA VALUES(7, 7);
INSERT INTO EXPESSURA VALUES(8, 8);
INSERT INTO EXPESSURA VALUES(9, 9);
INSERT INTO EXPESSURA VALUES(10, 10);
INSERT INTO EXPESSURA VALUES(11, 11);
INSERT INTO EXPESSURA VALUES(12, 12);
INSERT INTO EXPESSURA VALUES(13, 13);
INSERT INTO EXPESSURA VALUES(14, 14);
INSERT INTO EXPESSURA VALUES(15, 15);
INSERT INTO EXPESSURA VALUES(16, 16);
INSERT INTO EXPESSURA VALUES(17, 17);
INSERT INTO EXPESSURA VALUES(18, 18);
INSERT INTO EXPESSURA VALUES(19, 19);
INSERT INTO EXPESSURA VALUES(20, 20);

-------------------------------
-- Insert em Adesivos de vidro
--------------------------------
INSERT INTO ADESIVOS VALUES(1, 'Vermelho');
INSERT INTO ADESIVOS VALUES(2, 'Preto');
INSERT INTO ADESIVOS VALUES(3, 'Branco');
INSERT INTO ADESIVOS VALUES(4, 'Dourado');
INSERT INTO ADESIVOS VALUES(5, 'Amarelo');
INSERT INTO ADESIVOS VALUES(6, 'Prata');
INSERT INTO ADESIVOS VALUES(7, 'Cinza');
INSERT INTO ADESIVOS VALUES(8, 'Verde');
INSERT INTO ADESIVOS VALUES(9, 'Alumínio');
INSERT INTO ADESIVOS VALUES(10, 'Azul');

-------------------------------
-- Insert em Peliculas de vidro
--------------------------------
INSERT INTO PELICULAS VALUES(1, 'Jateada');
INSERT INTO PELICULAS VALUES(2, 'preto');
INSERT INTO PELICULAS VALUES(3, 'Incolor');
INSERT INTO PELICULAS VALUES(4, 'Dourado');
INSERT INTO PELICULAS VALUES(5, 'Amarelo');
INSERT INTO PELICULAS VALUES(6, 'Prata');
INSERT INTO PELICULAS VALUES(7, 'Cinza');
INSERT INTO PELICULAS VALUES(8, 'Verde');
INSERT INTO PELICULAS VALUES(9, 'Alumínio');
INSERT INTO PELICULAS VALUES(10,'Azul');