// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vidracaria_Portal.Data.Context;

namespace Vidracaria_Portal.Migrations
{
    [DbContext(typeof(VidracariaContext))]
    [Migration("20210315010126_TabelasDeCores")]
    partial class TabelasDeCores
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "a2febe6b-73cf-48e5-becf-f0143349da5f",
                            ConcurrencyStamp = "34b76e39-5c61-4f14-b09e-8becb5d35c51",
                            Name = "Administrador",
                            NormalizedName = "ADMINISTRADOR"
                        },
                        new
                        {
                            Id = "66760d1a-7cbd-4365-85a1-7bff1c5cc89e",
                            ConcurrencyStamp = "5f9c6b4b-0c3f-4dfe-bf55-9b879756babc",
                            Name = "Cliente",
                            NormalizedName = "CLIENTE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(85)
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(85)
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("RoleId")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "42ab97c4-0cbe-4535-958f-350fa587f38d",
                            RoleId = "a2febe6b-73cf-48e5-becf-f0143349da5f"
                        },
                        new
                        {
                            UserId = "f0ac269f-3b42-4a65-be1d-bd2588269def",
                            RoleId = "66760d1a-7cbd-4365-85a1-7bff1c5cc89e"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("Name")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Cadastros.AluminiosModel", b =>
                {
                    b.Property<decimal>("CodigoAluminio")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("CorCodigoCor")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("CorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<int>("EstoqueMaximo")
                        .HasColumnType("int");

                    b.Property<int>("EstoqueMinimo")
                        .HasColumnType("int");

                    b.Property<decimal>("ExpessuraCodigoExpessura")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ExpessuraId")
                        .HasColumnType("int");

                    b.Property<string>("Imagem")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NomeAluminio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("PrecoFabrica")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("CodigoAluminio");

                    b.HasIndex("CorCodigoCor");

                    b.HasIndex("ExpessuraCodigoExpessura");

                    b.ToTable("ALUMINIOS");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Cadastros.ClientesModel", b =>
                {
                    b.Property<decimal>("CodigoCliente")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CidadeCliente")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoCliente")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Imagem")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<int>("NumeroCasa")
                        .HasColumnType("int");

                    b.HasKey("CodigoCliente");

                    b.ToTable("CLIENTES");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Cadastros.FerragensModel", b =>
                {
                    b.Property<decimal>("CodigoFerragem")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("CorCodigoCor")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("CorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<int>("EstoqueMaximo")
                        .HasColumnType("int");

                    b.Property<int>("EstoqueMinimo")
                        .HasColumnType("int");

                    b.Property<string>("Imagem")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Marca")
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<string>("NomeFerragem")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<decimal>("PrecoFabrica")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("CodigoFerragem");

                    b.HasIndex("CorCodigoCor");

                    b.ToTable("FERRAGENS");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Cadastros.ProdutosModel", b =>
                {
                    b.Property<decimal>("Codigo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("CorCodigoCor")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("CorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<int>("EstoqueMaximo")
                        .HasColumnType("int");

                    b.Property<int>("EstoqueMinimo")
                        .HasColumnType("int");

                    b.Property<string>("Imagem")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("PrecoFabrica")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Codigo");

                    b.HasIndex("CorCodigoCor");

                    b.ToTable("PRODUTOS");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Cadastros.VidrosComunsModel", b =>
                {
                    b.Property<decimal>("CodigoVidro")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("CorCodigoCor")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("CorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<decimal>("EstoqueMaximo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("EstoqueMinimo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("ExpessuraCodigoExpessura")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ExpessuraId")
                        .HasColumnType("int");

                    b.Property<string>("Imagem")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Marca")
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<string>("NomeVidro")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<int>("PrecoFabrica")
                        .HasColumnType("int");

                    b.Property<int>("PrecoVenda")
                        .HasColumnType("int");

                    b.HasKey("CodigoVidro");

                    b.HasIndex("CorCodigoCor");

                    b.HasIndex("ExpessuraCodigoExpessura");

                    b.ToTable("VIDROS_COMUNS");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Cadastros.VidrosTemperadosModel", b =>
                {
                    b.Property<decimal>("CodigoVidro")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("CorCodigoCor")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("CorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<int>("EstoqueMaximo")
                        .HasColumnType("int");

                    b.Property<int>("EstoqueMinimo")
                        .HasColumnType("int");

                    b.Property<decimal?>("ExpessuraCodigoExpessura")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ExpessuraId")
                        .HasColumnType("int");

                    b.Property<string>("Imagem")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Marca")
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<string>("NomeVidro")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<decimal>("PrecoFabrica")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("CodigoVidro");

                    b.HasIndex("CorCodigoCor");

                    b.HasIndex("ExpessuraCodigoExpessura");

                    b.ToTable("VIDROS_TEMPERADOS");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Servicos.AprovadosModel", b =>
                {
                    b.Property<decimal>("CodigoAprovado")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<string>("Estado")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Imagem")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<int>("NumeroCasa")
                        .HasColumnType("int");

                    b.HasKey("CodigoAprovado");

                    b.ToTable("APROVADOS");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Servicos.ConcluidosModel", b =>
                {
                    b.Property<decimal>("CodigoConcluido")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<string>("Estado")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Imagem")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<int>("NumeroCasa")
                        .HasColumnType("int");

                    b.HasKey("CodigoConcluido");

                    b.ToTable("CONCLUIDOS");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Servicos.OrcamentosModel", b =>
                {
                    b.Property<decimal>("CodigoOrcamento")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<string>("Estado")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Imagem")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<int>("NumeroCasa")
                        .HasColumnType("int");

                    b.HasKey("CodigoOrcamento");

                    b.ToTable("ORCAMENTOS");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Servicos.PendentesModel", b =>
                {
                    b.Property<decimal>("CodigoPendentes")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<string>("Estado")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Imagem")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<int>("NumeroCasa")
                        .HasColumnType("int");

                    b.HasKey("CodigoPendentes");

                    b.ToTable("PENDENTES");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Cliente.ContatoModel", b =>
                {
                    b.Property<int>("CodigoContato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("DataContato")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataRetorno")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Retorno")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("CodigoContato");

                    b.ToTable("CONTATOS");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Selects.CoresModel", b =>
                {
                    b.Property<decimal>("CodigoCor")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("NomeCor")
                        .HasColumnType("text");

                    b.HasKey("CodigoCor");

                    b.ToTable("CORES");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Selects.CoresVidroComunsModel", b =>
                {
                    b.Property<decimal>("CodigoCor")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("NomeCor")
                        .HasColumnType("text");

                    b.HasKey("CodigoCor");

                    b.ToTable("CORES_VIDROS_COMUNS");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Selects.CoresVidrosTemperadosModel", b =>
                {
                    b.Property<decimal>("CodigoCor")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("NomeCor")
                        .HasColumnType("text");

                    b.HasKey("CodigoCor");

                    b.ToTable("CORES_VIDROS_TEMPERADOS");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Selects.ExpessurasModel", b =>
                {
                    b.Property<decimal>("CodigoExpessura")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Expessura")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("CodigoExpessura");

                    b.ToTable("EXPESSURA");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.UsuarioModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "42ab97c4-0cbe-4535-958f-350fa587f38d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2783c467-54cb-4e99-a608-1ee3dcec4a35",
                            DataNascimento = new DateTime(2021, 3, 14, 22, 1, 25, 133, DateTimeKind.Local).AddTicks(8367),
                            Email = "admin@vidracariaportal.com.br",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nome = "Admin",
                            NormalizedEmail = "ADMIN@VIDRACARIAPORTAL.COM.BR",
                            NormalizedUserName = "ADMIN@VIDRACARIAPORTAL.COM.BR",
                            PasswordHash = "AQAAAAEAACcQAAAAEMD3ZNrzuQykZu1BU6M+aQwvQ3zYfEMlv9RD79WWZcoqkTOFdGvCq11qxoc7sekYlg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "64665535",
                            TwoFactorEnabled = false,
                            UserName = "admin@vidracariaportal.com.br"
                        },
                        new
                        {
                            Id = "f0ac269f-3b42-4a65-be1d-bd2588269def",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "09f4f0af-7d49-458d-acd5-88be99f3c153",
                            DataNascimento = new DateTime(2002, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tavanoalexandre@outlook.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nome = "Alexandre Tavano Cardoso",
                            NormalizedEmail = "TAVANOALEXANDRE@OUTLOOK.COM",
                            NormalizedUserName = "TAVANOALEXANDRE@OUTLOOK.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEJ/h5sA2vgOxA9gvHC91FBoPylQHJWXxdlSXJd7Qp1P+UR9EnAoPVIF4q6YSDB8CYA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "45118907",
                            TwoFactorEnabled = false,
                            UserName = "tavanoalexandre@outlook.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Vidracaria_Portal.Models.UsuarioModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Vidracaria_Portal.Models.UsuarioModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vidracaria_Portal.Models.UsuarioModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Vidracaria_Portal.Models.UsuarioModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Cadastros.AluminiosModel", b =>
                {
                    b.HasOne("Vidracaria_Portal.Models.Selects.CoresModel", "Cor")
                        .WithMany()
                        .HasForeignKey("CorCodigoCor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vidracaria_Portal.Models.Selects.ExpessurasModel", "Expessura")
                        .WithMany()
                        .HasForeignKey("ExpessuraCodigoExpessura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cor");

                    b.Navigation("Expessura");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Cadastros.FerragensModel", b =>
                {
                    b.HasOne("Vidracaria_Portal.Models.Selects.CoresModel", "Cor")
                        .WithMany()
                        .HasForeignKey("CorCodigoCor");

                    b.Navigation("Cor");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Cadastros.ProdutosModel", b =>
                {
                    b.HasOne("Vidracaria_Portal.Models.Selects.CoresModel", "Cor")
                        .WithMany()
                        .HasForeignKey("CorCodigoCor");

                    b.Navigation("Cor");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Cadastros.VidrosComunsModel", b =>
                {
                    b.HasOne("Vidracaria_Portal.Models.Selects.CoresVidroComunsModel", "Cor")
                        .WithMany()
                        .HasForeignKey("CorCodigoCor");

                    b.HasOne("Vidracaria_Portal.Models.Selects.ExpessurasModel", "Expessura")
                        .WithMany()
                        .HasForeignKey("ExpessuraCodigoExpessura");

                    b.Navigation("Cor");

                    b.Navigation("Expessura");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Cadastros.VidrosTemperadosModel", b =>
                {
                    b.HasOne("Vidracaria_Portal.Models.Selects.CoresVidrosTemperadosModel", "Cor")
                        .WithMany()
                        .HasForeignKey("CorCodigoCor");

                    b.HasOne("Vidracaria_Portal.Models.Selects.ExpessurasModel", "Expessura")
                        .WithMany()
                        .HasForeignKey("ExpessuraCodigoExpessura");

                    b.Navigation("Cor");

                    b.Navigation("Expessura");
                });
#pragma warning restore 612, 618
        }
    }
}
