// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vidracaria_Portal.Data.Context;

namespace Vidracaria_Portal.Migrations
{
    [DbContext(typeof(VidracariaContext))]
    [Migration("20210325232331_Galeria")]
    partial class Galeria
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "826dc7b9-ae96-41c1-b1e0-654a4c43a703",
                            ConcurrencyStamp = "5eff258d-fd6a-4f71-96fd-48d47c8a71eb",
                            Name = "Administrador",
                            NormalizedName = "ADMINISTRADOR"
                        },
                        new
                        {
                            Id = "253af883-0f0b-4987-9c6d-ab8d214688f9",
                            ConcurrencyStamp = "b35254af-8a1c-42b3-85ae-03b3764eeb91",
                            Name = "Cliente",
                            NormalizedName = "CLIENTE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(85)
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(85)
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("RoleId")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "f3acf2c8-ec32-4006-8705-b7156dafd6ce",
                            RoleId = "826dc7b9-ae96-41c1-b1e0-654a4c43a703"
                        },
                        new
                        {
                            UserId = "03b7f777-4f52-490e-91f9-38fa087d30c1",
                            RoleId = "253af883-0f0b-4987-9c6d-ab8d214688f9"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("Name")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Cadastros.AgendaModel", b =>
                {
                    b.Property<int>("CodigoAgenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Assunto")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataLimite")
                        .HasColumnType("datetime");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CodigoAgenda");

                    b.ToTable("AGENDA");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Cadastros.AluminiosModel", b =>
                {
                    b.Property<int>("CodigoAluminio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<int>("EstoqueMaximo")
                        .HasColumnType("int");

                    b.Property<int>("EstoqueMinimo")
                        .HasColumnType("int");

                    b.Property<string>("Imagem")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NomeAluminio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("PrecoFabrica")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("CodigoAluminio");

                    b.HasIndex("CorId");

                    b.ToTable("ALUMINIOS");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Cadastros.ClientesModel", b =>
                {
                    b.Property<int>("CodigoCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CidadeCliente")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<string>("Documento")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("EstadoCliente")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<int>("NumeroCasa")
                        .HasColumnType("int");

                    b.HasKey("CodigoCliente");

                    b.ToTable("CLIENTES");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Cadastros.FerragensModel", b =>
                {
                    b.Property<int>("CodigoFerragem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<int>("EstoqueMaximo")
                        .HasColumnType("int");

                    b.Property<int>("EstoqueMinimo")
                        .HasColumnType("int");

                    b.Property<string>("Imagem")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Marca")
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<string>("NomeFerragem")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<decimal>("PrecoFabrica")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("CodigoFerragem");

                    b.HasIndex("CorId");

                    b.ToTable("FERRAGENS");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Cadastros.GaleriaModel", b =>
                {
                    b.Property<int>("CodigoGaleria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Imagem")
                        .HasColumnType("text");

                    b.HasKey("CodigoGaleria");

                    b.ToTable("GALERIA");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Cadastros.VidrosComunsModel", b =>
                {
                    b.Property<int>("CodigoVidro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AdesivoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<decimal>("EstoqueMaximo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("EstoqueMinimo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ExpessuraId")
                        .HasColumnType("int");

                    b.Property<string>("Imagem")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Marca")
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<string>("NomeVidro")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<int>("PeliculaId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoFabrica")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("CodigoVidro");

                    b.HasIndex("AdesivoId");

                    b.HasIndex("ExpessuraId");

                    b.HasIndex("PeliculaId");

                    b.ToTable("VIDROS_COMUNS");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Cadastros.VidrosTemperadosModel", b =>
                {
                    b.Property<int>("CodigoVidro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AdesivoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<int>("EstoqueMaximo")
                        .HasColumnType("int");

                    b.Property<int>("EstoqueMinimo")
                        .HasColumnType("int");

                    b.Property<int>("ExpessuraId")
                        .HasColumnType("int");

                    b.Property<string>("Imagem")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Marca")
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<string>("NomeVidro")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<int>("PeliculaId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoFabrica")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("CodigoVidro");

                    b.HasIndex("AdesivoId");

                    b.HasIndex("ExpessuraId");

                    b.HasIndex("PeliculaId");

                    b.ToTable("VIDROS_TEMPERADOS");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Servicos.AprovadosModel", b =>
                {
                    b.Property<decimal>("CodigoAprovado")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<string>("Estado")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Imagem")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<int>("NumeroCasa")
                        .HasColumnType("int");

                    b.HasKey("CodigoAprovado");

                    b.ToTable("APROVADOS");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Servicos.ConcluidosModel", b =>
                {
                    b.Property<decimal>("CodigoConcluido")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<string>("Estado")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Imagem")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<int>("NumeroCasa")
                        .HasColumnType("int");

                    b.HasKey("CodigoConcluido");

                    b.ToTable("CONCLUIDOS");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Servicos.OrcamentosModel", b =>
                {
                    b.Property<int>("CodigoOrcamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<string>("Estado")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Imagem")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<int>("NumeroCasa")
                        .HasColumnType("int");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("TipoId")
                        .HasColumnType("int");

                    b.Property<int?>("TipoServicoCodigoTipo")
                        .HasColumnType("int");

                    b.HasKey("CodigoOrcamento");

                    b.HasIndex("TipoServicoCodigoTipo");

                    b.ToTable("ORCAMENTOS");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Cliente.ContatoModel", b =>
                {
                    b.Property<int>("CodigoContato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("DataContato")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataRetorno")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Retorno")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("CodigoContato");

                    b.ToTable("CONTATOS");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Selects.AdesivoModel", b =>
                {
                    b.Property<int>("CodigoAdesivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("CodigoAdesivo");

                    b.ToTable("ADESIVOS");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Selects.CoresModel", b =>
                {
                    b.Property<int>("CodigoCor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NomeCor")
                        .HasColumnType("text");

                    b.HasKey("CodigoCor");

                    b.ToTable("CORES");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Selects.ExpessurasModel", b =>
                {
                    b.Property<int>("CodigoExpessura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Expessura")
                        .HasColumnType("int");

                    b.HasKey("CodigoExpessura");

                    b.ToTable("EXPESSURA");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Selects.PeliculasModel", b =>
                {
                    b.Property<int>("CodigoPelicula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("CodigoPelicula");

                    b.ToTable("PELICULAS");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Selects.TipoDeServicosModel", b =>
                {
                    b.Property<int>("CodigoTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasColumnType("text");

                    b.HasKey("CodigoTipo");

                    b.ToTable("TIPOS_DE_SERVICOS");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.UsuarioModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "f3acf2c8-ec32-4006-8705-b7156dafd6ce",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "804beb90-519a-4726-b9a0-5de3deb9955b",
                            Email = "admin@vidracariaportal.com.br",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nome = "Admin",
                            NormalizedEmail = "ADMIN@VIDRACARIAPORTAL.COM.BR",
                            NormalizedUserName = "ADMIN@VIDRACARIAPORTAL.COM.BR",
                            PasswordHash = "AQAAAAEAACcQAAAAELOEfjXLjWG8z9m0cfbiAS0QdvhQEhxsrwoNz9Dt4s5Sbvml9ESWw21+O+Fge6Bdag==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "25717600",
                            TwoFactorEnabled = false,
                            UserName = "admin@vidracariaportal.com.br"
                        },
                        new
                        {
                            Id = "03b7f777-4f52-490e-91f9-38fa087d30c1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "695a9adb-17a1-407d-ab31-2a39e52817ce",
                            Email = "tavanoalexandre@outlook.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nome = "Alexandre",
                            NormalizedEmail = "TAVANOALEXANDRE@OUTLOOK.COM",
                            NormalizedUserName = "TAVANOALEXANDRE@OUTLOOK.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEHLMJGdMW80Z0noC7ecNddpbBBxFNCxUG5XCHNkpvEGgYnJHxyWqHd2W9xU333Gdsw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "30131813",
                            TwoFactorEnabled = false,
                            UserName = "tavanoalexandre@outlook.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Vidracaria_Portal.Models.UsuarioModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Vidracaria_Portal.Models.UsuarioModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vidracaria_Portal.Models.UsuarioModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Vidracaria_Portal.Models.UsuarioModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Cadastros.AluminiosModel", b =>
                {
                    b.HasOne("Vidracaria_Portal.Models.Selects.CoresModel", "Cor")
                        .WithMany()
                        .HasForeignKey("CorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cor");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Cadastros.FerragensModel", b =>
                {
                    b.HasOne("Vidracaria_Portal.Models.Selects.CoresModel", "Cor")
                        .WithMany()
                        .HasForeignKey("CorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cor");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Cadastros.VidrosComunsModel", b =>
                {
                    b.HasOne("Vidracaria_Portal.Models.Selects.AdesivoModel", "Adesivo")
                        .WithMany()
                        .HasForeignKey("AdesivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vidracaria_Portal.Models.Selects.ExpessurasModel", "Expessura")
                        .WithMany()
                        .HasForeignKey("ExpessuraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vidracaria_Portal.Models.Selects.PeliculasModel", "Pelicula")
                        .WithMany()
                        .HasForeignKey("PeliculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adesivo");

                    b.Navigation("Expessura");

                    b.Navigation("Pelicula");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Cadastros.VidrosTemperadosModel", b =>
                {
                    b.HasOne("Vidracaria_Portal.Models.Selects.AdesivoModel", "Adesivo")
                        .WithMany()
                        .HasForeignKey("AdesivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vidracaria_Portal.Models.Selects.ExpessurasModel", "Expessura")
                        .WithMany()
                        .HasForeignKey("ExpessuraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vidracaria_Portal.Models.Selects.PeliculasModel", "Pelicula")
                        .WithMany()
                        .HasForeignKey("PeliculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adesivo");

                    b.Navigation("Expessura");

                    b.Navigation("Pelicula");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Servicos.OrcamentosModel", b =>
                {
                    b.HasOne("Vidracaria_Portal.Models.Selects.TipoDeServicosModel", "TipoServico")
                        .WithMany()
                        .HasForeignKey("TipoServicoCodigoTipo");

                    b.Navigation("TipoServico");
                });
#pragma warning restore 612, 618
        }
    }
}
