// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vidracaria_Portal.Data.Context;

namespace Vidracaria_Portal.Migrations
{
    [DbContext(typeof(VidracariaContext))]
    [Migration("20210329212826_Ajuste02")]
    partial class Ajuste02
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "bb483eb9-4e61-4adf-93db-819f132e7604",
                            ConcurrencyStamp = "6e274051-06f1-462b-bc67-0e651b5ff1ab",
                            Name = "Administrador",
                            NormalizedName = "ADMINISTRADOR"
                        },
                        new
                        {
                            Id = "3f1ba507-91fa-4101-aaea-7976d1eeb2e7",
                            ConcurrencyStamp = "5d6ae7c2-1b70-434b-a6ff-71b92985d563",
                            Name = "Cliente",
                            NormalizedName = "CLIENTE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(85)
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(85)
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("RoleId")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "866c5391-29c3-42fd-8850-d98b0d5465db",
                            RoleId = "bb483eb9-4e61-4adf-93db-819f132e7604"
                        },
                        new
                        {
                            UserId = "98a55741-73cc-4ce7-92b8-4c2c1c0578d5",
                            RoleId = "3f1ba507-91fa-4101-aaea-7976d1eeb2e7"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("Name")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Cadastros.AgendaModel", b =>
                {
                    b.Property<int>("CodigoAgenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Assunto")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataLimite")
                        .HasColumnType("datetime");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CodigoAgenda");

                    b.ToTable("AGENDA");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Cadastros.AluminiosModel", b =>
                {
                    b.Property<int>("CodigoAluminio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<int>("EstoqueMaximo")
                        .HasColumnType("int");

                    b.Property<int>("EstoqueMinimo")
                        .HasColumnType("int");

                    b.Property<string>("Imagem")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NomeAluminio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("PrecoFabrica")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("CodigoAluminio");

                    b.HasIndex("CorId");

                    b.ToTable("ALUMINIOS");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Cadastros.ClientesModel", b =>
                {
                    b.Property<int>("CodigoCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CidadeCliente")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<string>("Documento")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("EstadoCliente")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<int>("NumeroCasa")
                        .HasColumnType("int");

                    b.HasKey("CodigoCliente");

                    b.ToTable("CLIENTES");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Cadastros.FerragensModel", b =>
                {
                    b.Property<int>("CodigoFerragem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<int>("EstoqueMaximo")
                        .HasColumnType("int");

                    b.Property<int>("EstoqueMinimo")
                        .HasColumnType("int");

                    b.Property<string>("Imagem")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Marca")
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<string>("NomeFerragem")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<decimal>("PrecoFabrica")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("CodigoFerragem");

                    b.HasIndex("CorId");

                    b.ToTable("FERRAGENS");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Cadastros.GaleriaModel", b =>
                {
                    b.Property<int>("CodigoGaleria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Imagem")
                        .HasColumnType("text");

                    b.HasKey("CodigoGaleria");

                    b.ToTable("GALERIA");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Cadastros.ServicosModel", b =>
                {
                    b.Property<int>("CodigoServico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Imagem")
                        .HasColumnType("text");

                    b.Property<string>("NomeServico")
                        .HasColumnType("text");

                    b.HasKey("CodigoServico");

                    b.ToTable("SERVICOS");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Cadastros.TimeModel", b =>
                {
                    b.Property<int>("CodigoTIme")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cargo")
                        .HasColumnType("text");

                    b.Property<string>("Imagem")
                        .HasColumnType("text");

                    b.Property<string>("LinkFacebook")
                        .HasColumnType("text");

                    b.Property<string>("LinkImagem")
                        .HasColumnType("text");

                    b.Property<string>("NomeTime")
                        .HasColumnType("text");

                    b.HasKey("CodigoTIme");

                    b.ToTable("NOSSO_TIME");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Cadastros.VidrosComunsModel", b =>
                {
                    b.Property<int>("CodigoVidro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AdesivoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<decimal>("EstoqueMaximo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("EstoqueMinimo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ExpessuraId")
                        .HasColumnType("int");

                    b.Property<string>("Imagem")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Marca")
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<string>("NomeVidro")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<int>("PeliculaId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoFabrica")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("CodigoVidro");

                    b.HasIndex("AdesivoId");

                    b.HasIndex("ExpessuraId");

                    b.HasIndex("PeliculaId");

                    b.ToTable("VIDROS_COMUNS");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Cadastros.VidrosTemperadosModel", b =>
                {
                    b.Property<int>("CodigoVidro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AdesivoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<int>("EstoqueMaximo")
                        .HasColumnType("int");

                    b.Property<int>("EstoqueMinimo")
                        .HasColumnType("int");

                    b.Property<int>("ExpessuraId")
                        .HasColumnType("int");

                    b.Property<string>("Imagem")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Marca")
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<string>("NomeVidro")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<int>("PeliculaId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoFabrica")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("CodigoVidro");

                    b.HasIndex("AdesivoId");

                    b.HasIndex("ExpessuraId");

                    b.HasIndex("PeliculaId");

                    b.ToTable("VIDROS_TEMPERADOS");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Servicos.AprovadosModel", b =>
                {
                    b.Property<int>("CodigoAprovado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("CodigoOrcamento")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<string>("Estado")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Imagem")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<int>("NumeroCasa")
                        .HasColumnType("int");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("TipoId")
                        .HasColumnType("int");

                    b.Property<int?>("TipoServicoCodigoTipo")
                        .HasColumnType("int");

                    b.Property<string>("Valor")
                        .HasColumnType("text");

                    b.HasKey("CodigoAprovado");

                    b.HasIndex("TipoServicoCodigoTipo");

                    b.ToTable("APROVADOS");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Servicos.ConcluidosModel", b =>
                {
                    b.Property<int>("CodigoConcluido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("CodigoAprovados")
                        .HasColumnType("int");

                    b.Property<int>("CodigoOrcamento")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<string>("Estado")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Imagem")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<int>("NumeroCasa")
                        .HasColumnType("int");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("TipoId")
                        .HasColumnType("int");

                    b.Property<int?>("TipoServicoCodigoTipo")
                        .HasColumnType("int");

                    b.Property<string>("Valor")
                        .HasColumnType("text");

                    b.HasKey("CodigoConcluido");

                    b.HasIndex("TipoServicoCodigoTipo");

                    b.ToTable("CONCLUIDOS");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Servicos.OrcamentosModel", b =>
                {
                    b.Property<int>("CodigoOrcamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<string>("Estado")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Imagem")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<int>("NumeroCasa")
                        .HasColumnType("int");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("TipoId")
                        .HasColumnType("int");

                    b.Property<int?>("TipoServicoCodigoTipo")
                        .HasColumnType("int");

                    b.Property<string>("Valor")
                        .HasColumnType("text");

                    b.HasKey("CodigoOrcamento");

                    b.HasIndex("TipoServicoCodigoTipo");

                    b.ToTable("ORCAMENTOS");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Cliente.ContatoModel", b =>
                {
                    b.Property<int>("CodigoContato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("DataContato")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataRetorno")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Retorno")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("CodigoContato");

                    b.ToTable("CONTATOS");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Selects.AdesivoModel", b =>
                {
                    b.Property<int>("CodigoAdesivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("CodigoAdesivo");

                    b.ToTable("ADESIVOS");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Selects.CoresModel", b =>
                {
                    b.Property<int>("CodigoCor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NomeCor")
                        .HasColumnType("text");

                    b.HasKey("CodigoCor");

                    b.ToTable("CORES");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Selects.ExpessurasModel", b =>
                {
                    b.Property<int>("CodigoExpessura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Expessura")
                        .HasColumnType("int");

                    b.HasKey("CodigoExpessura");

                    b.ToTable("EXPESSURA");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Selects.PeliculasModel", b =>
                {
                    b.Property<int>("CodigoPelicula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("CodigoPelicula");

                    b.ToTable("PELICULAS");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Selects.TipoDeServicosModel", b =>
                {
                    b.Property<int>("CodigoTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasColumnType("text");

                    b.HasKey("CodigoTipo");

                    b.ToTable("TIPOS_DE_SERVICOS");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.UsuarioModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "866c5391-29c3-42fd-8850-d98b0d5465db",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4c8d11d1-cb4d-4a3d-8b4d-869a4ba7d07b",
                            Email = "admin@vidracariaportal.com.br",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nome = "Admin",
                            NormalizedEmail = "ADMIN@VIDRACARIAPORTAL.COM.BR",
                            NormalizedUserName = "ADMIN@VIDRACARIAPORTAL.COM.BR",
                            PasswordHash = "AQAAAAEAACcQAAAAEDz1AOiCd83NhjbX33Ia7Oc6oyBjWY9PakGQu5prUryC95hJN2nWFj/XiiPj2xbofg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "37966223",
                            TwoFactorEnabled = false,
                            UserName = "admin@vidracariaportal.com.br"
                        },
                        new
                        {
                            Id = "98a55741-73cc-4ce7-92b8-4c2c1c0578d5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1a01d314-dc47-4d06-940f-e8994bbabdf5",
                            Email = "tavanoalexandre@outlook.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nome = "Alexandre",
                            NormalizedEmail = "TAVANOALEXANDRE@OUTLOOK.COM",
                            NormalizedUserName = "TAVANOALEXANDRE@OUTLOOK.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEOqC6F0OTeUFqzK/LaKyHSChjsehGQCZsmh61109oiy5sLWHcn25bPNoHzJUf+pszg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6151694",
                            TwoFactorEnabled = false,
                            UserName = "tavanoalexandre@outlook.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Vidracaria_Portal.Models.UsuarioModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Vidracaria_Portal.Models.UsuarioModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vidracaria_Portal.Models.UsuarioModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Vidracaria_Portal.Models.UsuarioModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Cadastros.AluminiosModel", b =>
                {
                    b.HasOne("Vidracaria_Portal.Models.Selects.CoresModel", "Cor")
                        .WithMany()
                        .HasForeignKey("CorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cor");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Cadastros.FerragensModel", b =>
                {
                    b.HasOne("Vidracaria_Portal.Models.Selects.CoresModel", "Cor")
                        .WithMany()
                        .HasForeignKey("CorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cor");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Cadastros.VidrosComunsModel", b =>
                {
                    b.HasOne("Vidracaria_Portal.Models.Selects.AdesivoModel", "Adesivo")
                        .WithMany()
                        .HasForeignKey("AdesivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vidracaria_Portal.Models.Selects.ExpessurasModel", "Expessura")
                        .WithMany()
                        .HasForeignKey("ExpessuraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vidracaria_Portal.Models.Selects.PeliculasModel", "Pelicula")
                        .WithMany()
                        .HasForeignKey("PeliculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adesivo");

                    b.Navigation("Expessura");

                    b.Navigation("Pelicula");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Cadastros.VidrosTemperadosModel", b =>
                {
                    b.HasOne("Vidracaria_Portal.Models.Selects.AdesivoModel", "Adesivo")
                        .WithMany()
                        .HasForeignKey("AdesivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vidracaria_Portal.Models.Selects.ExpessurasModel", "Expessura")
                        .WithMany()
                        .HasForeignKey("ExpessuraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vidracaria_Portal.Models.Selects.PeliculasModel", "Pelicula")
                        .WithMany()
                        .HasForeignKey("PeliculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adesivo");

                    b.Navigation("Expessura");

                    b.Navigation("Pelicula");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Servicos.AprovadosModel", b =>
                {
                    b.HasOne("Vidracaria_Portal.Models.Selects.TipoDeServicosModel", "TipoServico")
                        .WithMany()
                        .HasForeignKey("TipoServicoCodigoTipo");

                    b.Navigation("TipoServico");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Servicos.ConcluidosModel", b =>
                {
                    b.HasOne("Vidracaria_Portal.Models.Selects.TipoDeServicosModel", "TipoServico")
                        .WithMany()
                        .HasForeignKey("TipoServicoCodigoTipo");

                    b.Navigation("TipoServico");
                });

            modelBuilder.Entity("Vidracaria_Portal.Models.Administrador.Servicos.OrcamentosModel", b =>
                {
                    b.HasOne("Vidracaria_Portal.Models.Selects.TipoDeServicosModel", "TipoServico")
                        .WithMany()
                        .HasForeignKey("TipoServicoCodigoTipo");

                    b.Navigation("TipoServico");
                });
#pragma warning restore 612, 618
        }
    }
}
